---
title: "What can I get you?"
format: html
---

# List of publications
*From newest to oldest*


**5. Revisiting fully residually free Demushkin groups** (2026). Joint with Pavel Zalesski. Submitted. On Arxiv: [https://arxiv.org/abs/2603.16814](https://arxiv.org/abs/2603.16814)

::: {.callout-note title="Abstract" collapse="true" appearance="minimal"}
We establish new examples and non-examples of pro-$p$ limit groups among the class of Demushkin groups, that is, pro-$p$ Poincaré duality groups of dimension $2$.
:::

**4. Profinite detection of free products and free factors** (2026). Joint with Andrei Jaikin and Pavel Zalesski. Submitted. On Arxiv: [https://arxiv.org/abs/2603.16674](https://arxiv.org/abs/2603.16674)

::: {.callout-note title="Abstract" collapse="true" appearance="minimal"}
Let $G$ be the fundamental group of a graph of finitely generated virtually free groups with virtually cyclic edge groups. We show that $G$ is cohomologically good if $G$ is residually finite. If $G$ is LERF, we prove that $G$ splits non-trivially as a free product if and only if its profinite completion $\widehat{G}$ splits non-trivially as a free profinite product. Moreover, we are able to detect one-ended free factors of $G$ from $\widehat{G}$. As an application, we deduce that any profinitely rigid word in a finitely generated free group is universally profinitely rigid.
:::

**3. Asymptotics of rational representations for algebraic groups** (2024). Joint with Lander Guerrero Sánchez. Submitted. On Arxiv: [https://arxiv.org/abs/2405.17360](https://arxiv.org/abs/2405.17360)

::: {.callout-note title="Abstract" collapse="true" appearance="minimal"}
We study the asymptotic behaviour of the cohomology of subgroups $\Gamma$ of an algebraic group $G$ with coefficients in the various irreducible rational representations of $G$ and raise a conjecture about it. Namely, we expect that the dimensions of these cohomology groups approximate the $\ell^2$-Betti numbers of $\Gamma$ with a controlled error term. We provide positive answers when $G$ is a product of copies of $\mathrm{SL}_2$. As an application, we obtain new proofs of J. Lott's and W. Lück's computation of the $\ell^2$-Betti numbers of hyperbolic 3-manifolds and W. Fu's upper bound on the growth of cusp forms for non totally real fields, which is sharp in the imaginary quadractic case.
:::

**2. Sylvester domains and pro-$p$ groups** (2024). Joint with Andrei Jaikin-Zapirain. In Documenta Mathematica (Vol. 31, Issue 2). [https://doi.org/10.4171/dm/1034](https://doi.org/10.4171/dm/1034). Also on ArXiv: [https://arxiv.org/abs/2402.14130](https://arxiv.org/abs/2402.14130)

::: {.callout-note title="Abstract" collapse="true" appearance="minimal"}
Let $G$ be a finitely generated torsion-free pro-$p$ group containing an open free-by-$\mathbb{Z}_p$ pro-$p$ subgroup. We show that the completed group algebra $\mathbb{F}_p[\![G]\!]$ is a Sylvester domain. Moreover the inner rank $\mathrm{irk}_{\mathbb{F}_p[\![G]\!]}(A)$ of a matrix $A$ over $\mathbb{F}_p[\![G]\!]$ can be calculated by approximation by ranks corresponding to finite quotients of $G$. As a consequence, we obtain a particular case of the mod $p$ Lück approximation for abstract finitely generated subgroups of free-by-$\mathbb{Z}_p$ pro-$p$ groups.
:::

**1. Inertia of retracts of Demushkin groups** (2022). In Journal of Group Theory (Vol. 26, Issue 3). [https://doi.org/10.1515/jgth-2022-0055](https://doi.org/10.1515/jgth-2022-0055). Also on ArXiv: [https://arxiv.org/abs/2111.03060](https://arxiv.org/abs/2111.03060).

::: {.callout-note title="Abstract" collapse="true" appearance="minimal"}
Exploring inequalities regarding the rank and relation gradients of pro-$p$ modules and building upon recent results of Y. Antolín, A. Jaikin-Zapirain and M. Shusterman, we prove that every retract of a Demushkin group is inert in the sense of the Dicks-Ventura Inertia Conjecture.
::: 

# PhD Thesis

[Defense slides](resources/slides/defense/defense.html)

My [PhD thesis](resources/MendesdaSilvaeSouza_HenriqueAugusto_tesis.pdf) titled "Ranks over pro-$p$ groups", presented under the advice of [Andrei Jaikin](https://andreijaikin.wordpress.com/), explores the space of rank functions on completed group algebras of pro-$p$ groups. A Sylvester rank function on a ring is an axiomized shadow of how the usual rank of matrices in linear algebra behaves on a field. However, for a general ring $R$, the space $\mathbb{P}(R)$ of rank functions defined on the set $\operatorname{Mat}(R)$ of matrices over $R$ can be immense. Nonetheless, there are special classes of rings $R$ that admit "canonical" rank functions, such as the Ore rank function for Ore domains and the normalized rank for completed group $\mathbb{F}_p$-algebras of pro-$p$ groups. 

Another notion that is closely related to rank functions is the *inner rank* of a matrix $A$, defined as the smallest integer $k$ such that $A$ factors as $BC$ for some $n\times k$ matrix $B$ and some $k\times m$ matrix $C$. The inner rank does not satisfy in general the axioms of a Sylvester rank function -- the rings for which it does are called **Sylvester domains**. The first part of the thesis concerns itself with the question of which completed group algebras of finitely generated profinite groups are Syvlester domains. The attempted classification is approached in two directions: first, we prove that the groups in question must be torsion-free coherent pro-$p$ groups of cohomological dimension at most $2$. Afterwards, we expand the class of known examples by proving that group algebras of torsion-free virtually free-by-$\mathbb{Z}_p$ pro-$p$ groups over finite fields of characteristic $p$ are Sylvester domains. A remarkable theorem is that this property is a commensurability invariant for torsion-free pro-$p$ groups, which is false for complex group algebras of discrete groups.

Since the space $\mathbb{P}(R)$ is a convex subset of a real vector space, we can also talk about *approximations* of rank functions. Another result of the this thesis is that for torsion-free virtually free-by-$\mathbb{Z}_p$ pro-$p$ groups, the inner rank on the completed group algebra can be approximated by the ranks coming from the regular representation of its finite quotients. The second part of the thesis concerns itself with a different kind of approximation phenomena, now on the space $\mathbb{P}(\mathbb{Z}_p[\![U]\!])$ of rank functions over the completed group $\mathbb{Z}_p$-ring of a uniform pro-$p$ group $U$, also called an *Iwasawa algebra*. Those rings are Ore domains, and therefore come endowed with a canonical rank function from its embedding in its Ore division ring of fractions. A classical theorem of M. Harris proves that this rank can be approximated by the ranks coming the regular representation of its finite quotients with a controlled error term.

We consider now a different kind of approximation when $U$ is split semisimple and simply-connected, viewed as an open subgroup of an algebraic group $\mathsf{G}$ over $\mathbb{Q}_p$. In this setting, $U$ comes with a plethora of finite-dimensional $\mathbb{Q}_p$ representations $U \to \mathsf{GL}(V_\lambda)$ coming from the rational representations of $\mathsf{G}$, where the indexing parameter $\lambda$ is the highest weight of the representation. The representations $V_\lambda$ behave very differently from the regular representation of the finite quotients of $U$, but we still conjecture that they can be used to approximate the Ore rank function with a controlled error as the weight $\lambda$ grows. We explain how this is the case for $\mathsf{G} = \prod_{i=1}^k \mathsf{SL}_2$, following the argument of W. Fu, and what are some of the difficulties in extending this to higher rank.

The final part of the thesis gives applications of these results to group algebras of discrete finitely generated groups: it proves Lück approximation in characteristic $p$ for finitely generated abstract subgroups of free-by-$\mathbb{Z}_p$ pro-$p$ groups, it shows how the conjectural apporximation for Iwasawa algebras yields asymptotic results on the cohomology of finitely generated subgroups of complex semisimple Lie groups, it gives a new proof of J. Lott and W. Lück's computation of the $\ell^2$-Betti numbers of topologically finite hyperbolic $3$-manifolds and explains how the asymptotic bounds on the cohomology of arithmetic lattices relates to the theory of automorphic forms.

# M.Sc. Thesis

[Defense slides](resources/mscdefense.pdf)

My [M.Sc. thesis](resources/gruposdedemushkin.pdf), presented under the advice of [Theo Zapata](https://mat.unb.br/~zapata/), explored the combinatorial properties of Dëmushkin groups. Its goal was to be a guide through recent results about Dëmushkin groups concerning the finiteness properties of subgroups and virtual retracts. More precisely, pro-$p$ analogues of Howson's theorem, the Hanna Neumann inequality, the presence of the virtual retractions property and the abscence of virtual decompositions as a free pro-$p$ product.

During my master degree, my research was focused on a particular class of topological groups called Dëmushkin groups. A Dëmushkin group is a pro-$p$ group that satisfies Poincaré duality in dimension 2, that is, $G$ is a Dëmushkin group if $\mathrm{H}^1(G,\mathbb{F}_p)$ is finite, $\mathrm{H}^2(G,\mathbb{F}_p)$ has dimension 1 and the cup product $\mathrm{H}^1(G,\mathbb{F}_p) \times \mathrm{H}^1(G,\mathbb{F}_p) \to \mathrm{H}^2(G,\mathbb{F}_p)$ is a non-degenerate bilinear form. Dëmushkin groups appear naturally as Galois groups of maximal $p$-extensions of local fields, as pro-$p$ completions of surface groups and as maximal pro-$p$ quotients of étale fundamental groups of smooth projective curves.

Dëmushkin groups have lots of great properties. They are topologically finitely generated and possess a topological presentation given by a single well known relation. They have strong hereditary, finiteness and virtual decomposition properties similar to those found in free pro-$p$ groups. There is a lot of research about them, and many important developments have been made in the past decades.

